# From https://model-checking.github.io/kani/install-github-ci.html
name: Kani CI
on:
  schedule:
    - cron: '59 23 * * *'       # midnight every day.
jobs:
  run-kani:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@v3

      - name: 'Run Kani on your code.'
        uses: model-checking/kani-github-action@v0.15
